### ISSUE TITLE
Secret Key 노출

### ISSUE THREAD

**Issue by shp7724** [wafflestudio19-5/team9-server#5]
저희 깃헙 레포에 Django 시크릿 키가 그대로 노출되어 있는 이슈가 있습니다.

시크릿 키 변경하고, 별도 파일로 분리해서 .gitignore에 추가하는 게 좋을 것 같습니다.

### 참고
- https://wayhome25.github.io/django/2017/07/11/django-settings-secret-key/

**Comment by jaejae2374** [comment]
확인했습니다.

**Comment by IHIHHIHI** [comment]
https://stackoverflow.com/questions/61670081/django-secret-key-setting-must-not-be-empty-with-github-workflow
시크릿 키 설정하고 ci 사용하는 경우에는 이러한 추가 작업도 필요할 것 같네요! 우선 회원가입/로그인 구현 후에 작업해보겠습니다. 그리고 만약 시간이 부족한 경우엔 우선 스프린트 2로 미뤄야겠네요..!

**Comment by IHIHHIHI** [comment]
https://leeceo97.tistory.com/42
데이터베이스 관련해서도 비슷한 이슈가 있네요.
